### ISSUE TITLE
[RelayMiner] Allow Mnemonic + Index Range in Config File to Simplify Bulk Key Management

### ISSUE THREAD

**Issue by jorgecuesta** [pokt-network/poktroll#1232]
## Objective
We need a more efficient way to manage thousands of keys in RelayMiner’s config file. Instead of referencing each [hex key by name](https://dev.poktroll.com/operate/configs/relayminer_config#default_signing_key_names), the user should be able to specify a mnemonic plus an index range.

## Origin Document
Currently, RelayMiner expects each key to be listed individually in the config, making large-scale key management cumbersome.

This is just an idea how it can be handled on RelayMiner configuration:

```yaml
...
# ... omit for simplicity

# same for suppliers.*.signing_key_names
default_signing_key_names:
  - name: mnemonic-seed-0
    mode: mnemonic
    from_index: 0
    to_index: 2999
  - name: supplier-xyz
    mode: hex
# ... omit for simplicity
```

Of course this means that `pocketd keys` should allow to generate or import a mnemonic seed as is and not just an specific index of it.

## Goals
- Allow specifying mnemonic-based keys (with index ranges) within the existing config file.  
- Reduce the size and complexity of config files when handling thousands of keys.  
- Ensure backwards compatibility for existing configurations.

## Deliverables
- [ ] Support for a “mnemonic” mode in the config that derives keys based on a provided seed and index range.  
- [ ] Config field(s) to differentiate between mnemonic- and hex-based keys (allowing the user to choose).  
- [ ] Documentation or examples demonstrating how to use mnemonic-based configuration.

## Non-goals / Non-deliverables
- Mixing mnemonic and hex definitions for the same key set (if that complicates implementation).

## Request for Comments (RFC):
1. Is the concept of “mode” (mnemonic vs. hex) viable within RelayMiner’s existing structure?
2. Should mixed modes (some mnemonic, some hex) be allowed in the same list, or separated under different fields?
3. Security implications or best practices to consider for storing mnemonic seeds?

Any feedback or alternative design proposals would be greatly appreciated. Thank you!
