### ISSUE TITLE
[RelayMiner] Questioning the Value of `publicly_exposed_endpoints` Configuration

### ISSUE THREAD

**Issue by jorgecuesta** [pokt-network/poktroll#1247]
### Core Concern

The current requirement to specify `publicly_exposed_endpoints` [1] in the RelayMiner configuration appears to add complexity without providing meaningful guarantees. While it validates that hostnames match between the supplier's staked information and configuration, it doesn't ensure actual service availability or proper infrastructure setup.

### Specific Issues

1. **No Infrastructure Validation**
   - The hostname match doesn't verify DNS resolution
   - No validation of reverse proxy configuration
   - No actual connectivity testing

2. **Additional Operational Overhead**
   - Operators must maintain an extra configuration
   - Makes setup process more complex
   - Potential for mismatches during updates or maintenance
   - Block the RelayMiner if not properly configured
   - Force the address to be stake (already talk here about why this is bad)

### Question for Discussion

Should we maintain this configuration requirement if it only provides hostname matching without actual infrastructure validation? The current approach seems to add complexity without providing meaningful security or operational guarantees.

Should we turn this setting as an optional one that is only required if you turn on `x_forwarded_host_lookup` [2] ? 
If yes, then this maybe need a better configuration options under something like `security` options.

e.g.
```yaml
suppliers:
- listen_url: http://0.0.0.0:8545
  service_config:
    backend_url: http://anvil:8547/
  service_id: anvil
  security:
    # this should be optional and replace `x_forwarded_host_lookup: false` [2] and `publicly_exposed_endpoints` [1]
    # so this can be "turn on" only if the operator needs/want because
    allowed_hostname: 
      - eth-rest.relayminer1.example.com
      - eth-rest.relayminer1.new-domain.com (following the idea of migrating domain from comments)
  
```

### References
1. https://github.com/pokt-network/poktroll/blob/main/pkg/relayer/proxy/server_builder.go#L48
2. https://github.com/pokt-network/poktroll/blob/main/pkg/relayer/proxy/sync.go#L57

**Comment by RawthiL** [comment]
+1 to this

I also struggled with this when trying to setup a single relayminer. 
It seems to lack real usage besides adding an insignificant amount of deterrence to changing the actual served endpoints (any bad actor can just change the code).

**Comment by Olshansk** [comment]
@RawthiL @jorgecuesta I talked about it with @red-0ne and @okdas and aligned on this feedback.

We're going to remove `publicly_exposed_endpoints` altogether.

Can you guys 👍 if it sounds good to you or leave a comment otherwise?

@bryanchriswhite Could you prioritize this tomorrow?

**Comment by jorgecuesta** [comment]
> [@RawthiL](https://github.com/RawthiL) [@jorgecuesta](https://github.com/jorgecuesta) I talked about it with [@red-0ne](https://github.com/red-0ne) and [@okdas](https://github.com/okdas) and aligned on this feedback.
> 
> We're going to remove `publicly_exposed_endpoints` altogether.
> 
> Can you guys 👍 if it sounds good to you or leave a comment otherwise?
> 
> [@bryanchriswhite](https://github.com/bryanchriswhite) Could you prioritize this tomorrow?

did you evaluate the possibility to instead of remove use/place it properly with better naming and make optional, like the example I made.

```yaml
suppliers:
- listen_url: http://0.0.0.0:8545
  service_config:
    backend_url: http://anvil:8547/
  service_id: anvil
  security:
    # this should be optional and replace `x_forwarded_host_lookup: false` [2] and `publicly_exposed_endpoints` [1]
    # so this can be "turn on" only if the operator needs/want because
    allowed_hostname: 
      - eth-rest.relayminer1.example.com
      - eth-rest.relayminer1.new-domain.com (following the idea of migrating domain from comments)
  
```

at the end im done with remove and leave the NR set this kind of "filter" on their reverse proxy, keep relayminer simpler so easier to deploy, but if u want for X reason keep it, take a look to my idea, otherwise 👍🏻
