### ISSUE TITLE
[RelayMiner] KeyManagement

### ISSUE THREAD

**Issue by RawthiL** [pokt-network/poktroll#1250]
## Objective

Allow the relayminer to accept keys in the form of `address:private_key`

## Origin Document

Current implementations of the relayminer need to use a keyring to work. Keys are loaded using a "signing_key_name" which refers to a keyring. Moreover, the existent helm-charts have the keyring names hardcoded (see https://github.com/pokt-network/helm-charts/blob/bbbff1f9a27cd22fc379aa563a9151b081a346c6/charts/relayminer/values.yaml#L64).

The current mechanism makes it hard to deploy the relayminer outside the provided enviroments.

## Goals

Being able to provide a simple file like:
```yaml
config:
  signing_key_name:
    address: <signer address>
    private_key: <signer private key>
```

**Creator**: @RawthiL
