### ISSUE TITLE
[RelayMiner] Add Metadata Headers to Backend calls

### ISSUE THREAD

**Issue by jorgecuesta** [pokt-network/poktroll#1257]
## Origin Document
The need arises from scenarios where the receiving backend needs specific headers to properly route and identify requests. For example, using these new headers enables advanced filtering and organizational capabilities, ensuring the corrected routing for each request.

Right now as an example I add this 2 lines at [1] to forward for example ServiceID and OperatorAddress

```go
header.Set("X-Pocket-Servicer", relayRequest.Meta.SupplierOperatorAddress)
header.Set("X-Pocket-Service", relayRequest.Meta.SessionHeader.ServiceId)
```

1. https://github.com/pokt-network/poktroll/blob/main/pkg/relayer/http_request.go#L64

This kind of feature does not hurts anyone, can be 100% optional and allows future works on custom backends move forward easily because the metadata is already delivered.

Headers can be hardcode and just declared into documentation about them, which are and what they hold.

## Goals
- Enable passing meta data through HTTP headers.
- Allow the backend service to consume these headers for flexible internal routing.
- Preserve original request structure and authentication while adding the new meta information.

## Deliverables
- [ ] Implement meta header injection.
- [ ] Add relevant tests to confirm headers are set correctly for various request scenarios.

## Non-goals / Non-deliverables
- Implementing or modifying the backend routing logic (that will be done elsewhere as needed).
- Changes related to authentication beyond adding basic headers.

## General deliverables
- [ ] **Comments**: Update source code comments to explain the purpose of the new headers.
- [ ] **Testing**: Add unit and/or E2E tests to ensure headers are set and can be read downstream.
- [ ] **Documentation**: Update any relevant internal docs or READMEs.

**Comment by RawthiL** [comment]
A simple use case for this feature is:
- You have two supplier addresses for the same service.
- You have two independent instances of `some_service` backends (as it should be ideally, 1 supplier = 1 backend)
- You want to deploy a single relayminer.

Using this, you can simply deploy a single relay miner as:
```yaml
    suppliers:
        - service_id: some_service
          signing_key_names: [supplier1, supplier2]
          service_config:
              backend_url: http://some-backend-router:9900
              publicly_exposed_endpoints:
              - "some public endpoint"
          listen_url: http://0.0.0.0:8545
          forward_identity_headers: true
```
and then use some other backend service (`some-backend-router:9900`) to re-route the packages using the `X-Pocket-Supplier` and `X-Pocket-Service` headers.
