### ISSUE TITLE
[relayminer] No error on wrong chain-id

### ISSUE THREAD

**Issue by RawthiL** [pokt-network/poktroll#1278]
## Objective

When the wrong 
endpoint wrong parameter is given in relayminer's `--chain-id`, the relayminer hangs instead of giving an error.

## Origin Document

Deplopying a relayminer pointing to:
```
    pocket_node:
        query_node_rpc_url: https://shannon-testnet-grove-rpc.beta.poktroll.com
        query_node_grpc_url: https://shannon-testnet-grove-grpc.beta.poktroll.com:443
        tx_node_rpc_url: https://shannon-testnet-grove-rpc.beta.poktroll.com
```
with parameters:
```
              pocketd relayminer \
                --keyring-backend test \
                --config /home/pocket/config.yaml \
                --grpc-insecure false \
                --log_level debug \
                --chain-id "pocket" \
                --gas-adjustment 1.5 \
                --gas-prices 0.0001upokt 
```
the client hangs without error. See that the parameter `--chain-id "pocket"` is wrong, it should be `--chain-id "pocket-beta" `

## Goals

Produce an error signaling misconfiguration, or any other hint of problem source.

**Creator**: @RawthiL @jorgecuesta
