### ISSUE TITLE
[Migration] Retrieving lost POKT

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#1442]
## Objective

Recover lost POKT in malformed Morse addresses.

## Origin Document

The [recovery allowlist](https://github.com/pokt-network/poktroll/blob/main/x/migration/recovery/recovery_allowlist.go) is missing accounts with malformed addresses that exist in the [mainnet snapshot export](https://raw.githubusercontent.com/pokt-network/poktroll/refs/heads/main/tools/scripts/migration/msg_import_morse_accounts_170616_2025-06-03.json).

Example: `a412c4d32323c1583018bc8ce9d6fbb78bd189b7eb7256064ddb02c31ae89d8a`) 

```bash
cat ./tools/scripts/migration/morse_state_export_170616_2025-06-03.json| grep -A 5 "a412c4d32323c1583018bc8ce9d6fbb78bd189b7eb7256064ddb02c31ae89d8a"
                        "address": "a412c4d32323c1583018bc8ce9d6fbb78bd189b7eb7256064ddb02c31ae89d8a",
                        "coins": [
                            {
                                "amount": "618057459311",
                                "denom": "upokt"
                            }
```

## Goals

- Recover lost POKT

## Deliverables

- [x] Find a way of generating a full list of malformed addresses. For example:
    - Iterate through the entire `msg_import_morse_accounts_170616_2025-06-03.json`
    - Identify anything that is not a hex encoded string of the right length
    - Add it to the list
- [x] Generate a full list of malformed addresses from the snapshot
- [x] Add the list to the `recovery_allowlist.go`
- [ ] Merge the changes in and deploy them from `main` through to `MainNet`
- [ ] Test recovering one malformed address in Alpha & Beta TestNet -> provide the example command
- [ ] New requirement in [this comment](https://github.com/pokt-network/poktroll/issues/1442#issuecomment-2957326295)

---

**Creator**: @Olshansk  
**Co-Owners**: @bryanchriswhite @ArtSabintsev

**Comment by ArtSabintsev** [comment]
- Exchange A
  - Morse Address 5eedf4989b385d69017f1a5597d6d3a09e81e03b 
  - Value 499,999.8 POKT
- Another entity
  - See addresses in Discord.

There are two more exchanges that may need assistance.

**Comment by Olshansk** [comment]
[pokt_suppliers_ZPL.csv](https://github.com/user-attachments/files/20662591/pokt_suppliers_ZPL.csv)

---

Using one example
```
Address,pubkey,unstake tx,Ledger address
012443b070e180de1f5cbc343e7d5d377acf4d93,b70cecae843f6e9d0f953928d10ea3dd6fbab019b5077bf35706c7d6b853a896,1D6DFB8F82FDD6C171D60FA99A20DA3148F279B608578CC569009B0A8C2D6C37,e09ca6063130c395be83a6be719014e09731b896
```

`Address`: 012443b070e180de1f5cbc343e7d5d377acf4d93
`pubkey`: b70cecae843f6e9d0f953928d10ea3dd6fbab019b5077bf35706c7d6b853a896
`unstake tx: `1D6DFB8F82FDD6C171D60FA99A20DA3148F279B608578CC569009B0A8C2D6C37
`ledger`: e09ca6063130c395be83a6be719014e09731b896

```bash
pocketd query migration show-morse-claimable-account 012443b070e180de1f5cbc343e7d5d377acf4d93 --network=beta
```

```yaml
morseClaimableAccount:
  application_stake:
    amount: "0"
    denom: upokt
  morse_output_address: E09CA6063130C395BE83A6BE719014E09731B896
  morse_src_address: 012443B070E180DE1F5CBC343E7D5D377ACF4D93
  supplier_stake:
    amount: "75100000000"
    denom: upokt
  unstaked_balance:
    amount: "95618492"
    denom: upokt
  unstaking_time: "2025-06-09T16:36:04.294004881Z"
```

```bash
pocketd query migration show-morse-claimable-account e09ca6063130c395be83a6be719014e09731b896 --network=beta
```

```yaml
morseClaimableAccount:
  application_stake:
    amount: "0"
    denom: upokt
  morse_src_address: E09CA6063130C395BE83A6BE719014E09731B896
  supplier_stake:
    amount: "0"
    denom: upokt
  unstaked_balance:
    amount: "2767282489413"
    denom: upokt
  unstaking_time: "0001-01-01T00:00:00Z"
```

`Address` and `Ledger`

Are:
- Valid
- in state export
- Claimable

Are not:
- recovery list

Next step:
- Add address to recovery list
- Add ledger to recovery list
