### ISSUE TITLE
[RelayMiner] Possible RelayMiner Memory Leak

### ISSUE THREAD

**Issue by Ajes1337** [pokt-network/poktroll#1448]
## Pick One or more

- [x] Can't service relays
- [ ] Can't scale my relay miner
- [ ] Can't deploy my relay miner
- [ ] Can't run my relay miner
- [ ] [Other]

## Priority

- [ ] P0 (ASAP)
- [x] P1 (one day)
- [ ] P2 (1-2 weeks)
- [ ] P3 (2-6 weeks)

## What? Why?

after 5-6 hours, relayminer has used up ~32gb memory, servicing 100k relays every 15min.

@okdas asked me to submit this issue, I have attached requested pprof snapshot

## Details

Your supplier's address is: `pokt1fpugdgaqxn5rarsqpuelg94n5jlryttz7uwmlu` (beta-testnet)

The command you use to start your relay miner is:

```bash
pocketd \
  relayminer start \
  --grpc-insecure=true \
  --log_level=info \
  --config=/home/ajes/relayminer.yaml \
  --chain-id=pocket-beta
```

Your Supplier's onchain configs are:

```yaml
owner_address: pokt1rvx0krv2ftwasprr88vxv0vcy05za64tgn3340
operator_address: pokt1fpugdgaqxn5rarsqpuelg94n5jlryttz7uwmlu
stake_amount: 104042000000upokt
default_rev_share_percent:
  pokt1rvx0krv2ftwasprr88vxv0vcy05za64tgn3340: 95
  pokt1fpugdgaqxn5rarsqpuelg94n5jlryttz7uwmlu: 5
services:
  - service_id: "eth"
    endpoints:
      - publicly_exposed_url: https://rm0001beta.kalorius.tech
        rpc_type: JSON_RPC
  - service_id: "scroll"
    endpoints:
      - publicly_exposed_url: https://rm0001beta.kalorius.tech
        rpc_type: JSON_RPC
  - service_id: "moonriver"
    endpoints:
      - publicly_exposed_url: https://rm0001beta.kalorius.tech
        rpc_type: JSON_RPC
  - service_id: "kaia"
    endpoints:
      - publicly_exposed_url: https://rm0001beta.kalorius.tech
        rpc_type: JSON_RPC
  - service_id: "evmos"
    endpoints:
      - publicly_exposed_url: https://rm0001beta.kalorius.tech
        rpc_type: JSON_RPC
  - service_id: "ink"
    endpoints:
      - publicly_exposed_url: https://rm0001beta.kalorius.tech
        rpc_type: JSON_RPC
  - service_id: "opbnb"
    endpoints:
      - publicly_exposed_url: https://rm0001beta.kalorius.tech
        rpc_type: JSON_RPC
  - service_id: "metis"
    endpoints:
      - publicly_exposed_url: https://rm0001beta.kalorius.tech
        rpc_type: JSON_RPC
  - service_id: "op"
    endpoints:
      - publicly_exposed_url: https://rm0001beta.kalorius.tech
        rpc_type: JSON_RPC
  - service_id: "taiko"
    endpoints:
      - publicly_exposed_url: https://rm0001beta.kalorius.tech
        rpc_type: JSON_RPC
  - service_id: "blast"
    endpoints:
      - publicly_exposed_url: https://rm0001beta.kalorius.tech
        rpc_type: JSON_RPC
  - service_id: "avax"
    endpoints:
      - publicly_exposed_url: https://rm0001beta.kalorius.tech
        rpc_type: JSON_RPC
  - service_id: "sonic"
    endpoints:
      - publicly_exposed_url: https://rm0001beta.kalorius.tech
        rpc_type: JSON_RPC
  - service_id: "gnosis"
    endpoints:
      - publicly_exposed_url: https://rm0001beta.kalorius.tech
        rpc_type: JSON_RPC
  - service_id: "zklink_nova"
    endpoints:
      - publicly_exposed_url: https://rm0001beta.kalorius.tech
        rpc_type: JSON_RPC
  - service_id: "pocket"
    endpoints:
      - publicly_exposed_url: https://rm0001beta.kalorius.tech
        rpc_type: JSON_RPC
```

Your RelayMiner's offchain configs are:

```yaml
default_signing_key_names:
  - supplier1 # name of the operator key in the keyring
  - supplier2 # name of the operator key in the keyring
  - supplier3 # name of the operator key in the keyring
  - supplier4 # name of the operator key in the keyring
  - supplier5 # name of the operator key in the keyring
  - supplier6 # name of the operator key in the keyring
  - supplier7 # name of the operator key in the keyring
  - supplier8 # name of the operator key in the keyring
  - supplier9 # name of the operator key in the keyring
  - supplier10 # name of the operator key in the keyring
  - supplier11 # name of the operator key in the keyring
  - supplier12 # name of the operator key in the keyring
  - supplier13 # name of the operator key in the keyring
  - supplier14 # name of the operator key in the keyring
  - supplier15 # name of the operator key in the keyring
  - supplier16 # name of the operator key in the keyring
  - supplier17 # name of the operator key in the keyring
  - supplier18 # name of the operator key in the keyring
  - supplier19 # name of the operator key in the keyring
  - supplier20 # name of the operator key in the keyring
  - supplier21 # name of the operator key in the keyring
  - supplier22 # name of the operator key in the keyring
  - supplier23 # name of the operator key in the keyring
  - supplier24 # name of the operator key in the keyring
  - supplier25 # name of the operator key in the keyring
  - supplier26 # name of the operator key in the keyring
  - supplier27 # name of the operator key in the keyring
  - supplier28 # name of the operator key in the keyring
  - supplier29 # name of the operator key in the keyring
  - supplier30 # name of the operator key in the keyring
  - supplier31 # name of the operator key in the keyring
  - supplier32 # name of the operator key in the keyring
  - supplier33 # name of the operator key in the keyring
  - supplier34 # name of the operator key in the keyring
  - supplier35 # name of the operator key in the keyring
  - supplier36 # name of the operator key in the keyring
  - supplier37 # name of the operator key in the keyring
  - supplier38 # name of the operator key in the keyring
  - supplier39 # name of the operator key in the keyring
  - supplier40 # name of the operator key in the keyring
  - supplier41 # name of the operator key in the keyring
  - supplier42 # name of the operator key in the keyring
smt_store_path: /home/ajes/.pocket/smt
pocket_node:
  query_node_rpc_url: tcp://localhost:26657
  query_node_grpc_url: tcp://localhost:9090
  tx_node_rpc_url: tcp://localhost:26657
suppliers:
  - service_id: eth
    listen_url: http://0.0.0.0:8545
    service_config:
      backend_url: http://192.168.1.148:8520/secret/F00C
  - service_id: scroll
    listen_url: http://0.0.0.0:8545
    service_config:
      backend_url: http://192.168.1.148:8520/secret/F024
  - service_id: moonriver
    listen_url: http://0.0.0.0:8545
    service_config:
      backend_url: http://192.168.1.148:8520/secret/F01A
  - service_id: kaia
    listen_url: http://0.0.0.0:8545
    service_config:
      backend_url: http://192.168.1.148:8520/secret/F016
  - service_id: evmos
    listen_url: http://0.0.0.0:8545
    service_config:
      backend_url: http://192.168.1.148:8520/secret/F00F
  - service_id: ink
    listen_url: http://0.0.0.0:8545
    service_config:
      backend_url: http://192.168.1.148:8520/secret/F032
  - service_id: opbnb
    listen_url: http://0.0.0.0:8545
    service_config:
      backend_url: http://192.168.1.148:8520/secret/F01F
  - service_id: metis
    listen_url: http://0.0.0.0:8545
    service_config:
      backend_url: http://192.168.1.148:8520/secret/F018
  - service_id: op
    listen_url: http://0.0.0.0:8545
    service_config:
      backend_url: http://192.168.1.148:8520/secret/F01D
  - service_id: taiko
    listen_url: http://0.0.0.0:8545
    service_config:
      backend_url: http://192.168.1.148:8520/secret/F027
  - service_id: blast
    listen_url: http://0.0.0.0:8545
    service_config:
      backend_url: http://192.168.1.148:8520/secret/F008
  - service_id: avax
    listen_url: http://0.0.0.0:8545
    service_config:
      backend_url: http://192.168.1.148:8520/secret/F003
  - service_id: sonic
    listen_url: http://0.0.0.0:8545
    service_config:
      backend_url: http://192.168.1.148:8520/secret/F02D
  - service_id: gnosis
    listen_url: http://0.0.0.0:8545
    service_config:
      backend_url: http://192.168.1.148:8520/secret/F013
  - service_id: zklink_nova
    listen_url: http://0.0.0.0:8545
    service_config:
      backend_url: http://192.168.1.148:8520/secret/F02A
  - service_id: pocket
    listen_url: http://0.0.0.0:8545
    service_config:
      backend_url: http://192.168.1.148:8520/secret/F02A
metrics:
  enabled: true
  addr: :19090
pprof:
  enabled: false
  addr: localhost:6060
ping:
  enabled: false
  addr: localhost:8081
```

---

**Creator**: [@Ajes1337]
**Co-Owners**: [@Olshansk]

[heap_profile2.zip](https://github.com/user-attachments/files/20646694/heap_profile2.zip)

**Comment by Olshansk** [comment]
@Ajes1337 

A couple of questions:

1. I see the issues w.r.t memory. Question: can you not service relays at all or does your relay miner not scale?
2. Can you share the command you used to retrieve the heap profile? I want to ensure no missing edge cases.

**Comment by Ajes1337** [comment]
> [@Ajes1337](https://github.com/Ajes1337)
> 
> A couple of questions:
> 
> 1. I see the issues w.r.t memory. Question: can you not service relays at all or does your relay miner not scale?
> 2. Can you share the command you used to retrieve the heap profile? I want to ensure no missing edge cases.

I used the command: "curl -o heap_profile2.pprof http://localhost:6060/debug/pprof/heap"

I can service relays, up until my lxc container runs out of allocated memory.

I have temporary fixed it by auto-restarting relayminer process when memory reaches a threshold.

here is proxmox-graph over used memory in container with relayminer, timespan is 1 day:

![Image](https://github.com/user-attachments/assets/8d70ba82-6999-4d21-b061-a8528ab38075)

**Comment by Ajes1337** [comment]
> [@Ajes1337](https://github.com/Ajes1337) I also want to set some expectations that we'll aim to fix in the second half of the week.
> 
> I understand (and agree) it's a really big issue, but there's only so much we can do at once.
> 
> Will aim to get to it sooner if possible.
> 
> cc [@fredteumer](https://github.com/fredteumer)

ye, its not "blocking" for me, just wanted to make you guys aware of what I experience, I would think that other suppliers will have bigger trouble than me, if they dont have a auto-restart system.. 😅

**Comment by Ajes1337** [comment]
after messing around with the relayminer's start flags, adding:  --gas-adjustment=1.3 --gas-prices=0.00001upokt

there dosnt seem to be any noticeable memoryleak anymore (it is still processing 50% of same amount of relays as before)

I did however also change the line-breaks in the yaml files (supplierConfig.yaml, and relayminerConfig.yaml) to linux endings, and not windows-endings:  

```cs
relayminerYaml = relayminerYaml.ReplaceLineEndings("\n");
```

![Image](https://github.com/user-attachments/assets/06148c37-8b6a-498f-bb78-c2bc261768f1)

**Comment by easy2stake** [comment]
I have a similar thread here @Ajes1337  :

https://github.com/pokt-network/poktroll/issues/1455

I think we're hitting the same issue. And I think the leak is directly proportional (or maybe an exponential function) with the number of operators configured.

**Comment by okdas** [comment]
@Ajes1337 seems like pprof snapshot was taken off the full node, not relayminer. They might have their 6060 ports collided - you can change which port pprof endpoint is available on relayminer:

```yaml
pprof:
  enabled: true
  addr: localhost:6060 # <- port here
```


Most important - heap profile:
```bash
curl -o heap_profile.pprof http://localhost:6060/debug/pprof/heap
```

Also helpful - goroutine profile:
```bash
curl -o goroutine_profile.pprof http://localhost:6060/debug/pprof/goroutine
```
