### ISSUE TITLE
[BUG][SUPPLIER] Claiming Morse supplier fails with <1 POKT balance due to insufficient funds error

### ISSUE THREAD

**Issue by kaelabbott** [pokt-network/poktroll#1450]
## Objective

Unable to claim a Morse account with less than 1 POKT due to a `FailedPrecondition` RPC error, which prevents wallet creation and funding.

## Origin Document

While using the `claim-suppliers` command, I encountered an error preventing the creation of new Morse wallets with a balance under 1 POKT. As a result, the wallets are not created, making it impossible to fund them afterward.

Morse address example: `e3ea1d6fc7c77188437ed2b6c3cd49265869429b`

I'm using the following command:

```
pocketd tx migration claim-suppliers --from "signer" --morse-private-keys-file "bulk.json" --stake-template-file "supplier_stake.yaml" --home "nodes" --keyring-backend test --output-file "supplier_output.json" --gas=auto --gas-prices=0.01upokt --gas-adjustment=1.5 --node https://rpc.shannon-mainnet.eu.nodefleet.net/ --network "main"
```

I also tried funding the signer account, but the issue persists:

https://shannon-mainnet.trustsoothe.io/account/pokt1gdg6adf72mrya07x56umlpy0qnygt4v7p9995q

**Comment by Olshansk** [comment]
## Investigation

Running this command

```bash
$ pocketd query migration show-morse-claimable-account e3ea1d6fc7c77188437ed2b6c3cd49265869429b --network=main --grpc-insecure=false
```

Shows that there is a valid supplier staked:

```yaml
morseClaimableAccount:
  application_stake:
    amount: "0"
    denom: upokt
  morse_output_address: A83ECC0A28C149789A6C2CEBB5F6E07C8A0248BD
  morse_src_address: E3EA1D6FC7C77188437ED2B6C3CD49265869429B
  supplier_stake:
    amount: "60000000000"
    denom: upokt
  unstaked_balance:
    amount: "529622"
    denom: upokt
  unstaking_time: "0001-01-01T00:00:00Z"
```

## Questions

> Unable to claim a Morse account with less than 1 POKT 

Q1. Do you mean `1 POKT` on `Morse` or `1 POKT` on `Shannon`?

> RPC error, which prevents wallet creation and funding.

Q2. Can you provide the full command and full RPC error?

>  As a result, the wallets are not created, making it impossible to fund them afterward.

Q3. What is the shannon address you're trying to use?

Q4. Did you make sure to fund the Shannon account with an `MACT` faucet as described [in the docs](https://dev.poktroll.com/explore/morse_migration/claiming_account#3-create-your-onchain-shannon-account)?

![Image](https://github.com/user-attachments/assets/fdf45f00-88cc-4806-9e25-cd62ec577459)
