### ISSUE TITLE
[Migration] morse output-address-key not needed for non-custodial supplier migration to mainnet

### ISSUE THREAD

**Issue by Ajes1337** [pokt-network/poktroll#1451]
# Background

Situation
 - I had 42 suppliers in total.
 - 9 of them were non-custodial.
 - These 9 suppliers required no special flags or arguments during migration—they worked out of the box.

Expectation
 - We assumed the Morse owner/output key would be needed to migrate a non-custodial supplier.
 - That does not seem to be the case.

⸻

Example (w/ Links & References)
 - Original non-custodial stake on Morse: [poktscan.com/node/d38d26](https://morse.poktscan.com/node/d38d260c9b7fa6a65409e05bbfbc5eeb2e1ec713)
Morse owner/output address: 4f31c0c7d6613a3e5becefb257b5b405d4484ec3
 - Migrated supplier on Shannon MainNet: [explorer.pocket.network/account/pokt1hgldz…](https://explorer.pocket.network/pocket-mainnet/account/pokt1hgldzstydutfc7qjwe6wqz3h6qc6fgfasaadrf)
 - Migration Tx: [Tx 19DA8…E11657](https://explorer.pocket.network/pocket-mainnet/tx/19DA8D8DDF686E59E7A736891B3CDB471B10FEDF411F47D1F4F9E62A13E11657)

Despite being non-custodial, I never used or referenced 4f31...4ec3 (the Morse output address).

⸻

Migration Command Used

```bash
pocketd tx migration claim-supplier \
  d38d260c9b7fa6a65409e05bbfbc5eeb2e1ec713 \
  /home/ajes/pokt_account_42.json \
  /home/ajes/supplier42.yaml \
  --from=supplier42 \
  --network=main \
  --yes
```

⸻

`supplier42.yaml`

```yaml
owner_address: pokt1rvx0krv2ftwasprr88vxv0vcy05za64tgn3340
operator_address: pokt1hgldzstydutfc7qjwe6wqz3h6qc6fgfasaadrf
# stake_amount: 60042000000upokt
default_rev_share_percent:
  pokt1rvx0krv2ftwasprr88vxv0vcy05za64tgn3340: 100
services:
  service_id: "eth"
  endpoints:
    publicly_exposed_url: https://rm0001.kalorius.tech/
    rpc_type: JSON_RPC
```

⸻

Maybe I’m hallucinating 😅

⸻

**Creator**: @Ajes1337
**Co-owners**: @Olshansk

**Comment by Olshansk** [comment]
_tl;dr Seems like the `owner_address` was simply claimed at an earlier time!_

Going to close this ticket out but please re-open if the explanation/investigation below is insufficient.

cc @fredteumer @TheFeloniousMonk

---

# Step 1: Check the `output_address` account: `d38d260c9b7fa6a65409e05bbfbc5eeb2e1ec713`

I run the following:

```bash
pocketd query migration show-morse-claimable-account 4F31C0C7D6613A3E5BECEFB257B5B405D4484EC3 --network=main --grpc-insecure=false
```

And found that it was claimed at height `97709`

```yaml
morseClaimableAccount:
  application_stake:
    amount: "0"
    denom: upokt
  claimed_at_height: "97709"
  morse_src_address: 4F31C0C7D6613A3E5BECEFB257B5B405D4484EC3
  shannon_dest_address: pokt1rvx0krv2ftwasprr88vxv0vcy05za64tgn3340
  supplier_stake:
    amount: "0"
    denom: upokt
  unstaked_balance:
    amount: "62463506502"
    denom: upokt
  unstaking_time: "0001-01-01T00:00:00Z"
```

## Step 2: Check the `operator_address` supplier: `d38d260c9b7fa6a65409e05bbfbc5eeb2e1ec713`

```
pocketd query migration show-morse-claimable-account d38d260c9b7fa6a65409e05bbfbc5eeb2e1ec713 --network=main --grpc-insecure=false
```

And found that it was claimed at height `109865` (coinciding with the [migration tx](https://explorer.pocket.network/pocket-mainnet/tx/19DA8D8DDF686E59E7A736891B3CDB471B10FEDF411F47D1F4F9E62A13E11657) you linked to):

```yaml
morseClaimableAccount:
  application_stake:
    amount: "0"
    denom: upokt
  claimed_at_height: "109865"
  morse_output_address: 4F31C0C7D6613A3E5BECEFB257B5B405D4484EC3
  morse_src_address: D38D260C9B7FA6A65409E05BBFBC5EEB2E1EC713
  shannon_dest_address: pokt1hgldzstydutfc7qjwe6wqz3h6qc6fgfasaadrf
  supplier_stake:
    amount: "60042000000"
    denom: upokt
  unstaked_balance:
    amount: "9523932"
    denom: upokt
  unstaking_time: "0001-01-01T00:00:00Z"
```
