### ISSUE TITLE
[RelayMiner] Integrate new RelayMiner configuration

### ISSUE THREAD

**Issue by red-0ne** [pokt-network/poktroll#271]
## Objective

The current  `RelayMiner` naive configuration file structure and parser is lacking capabilities to handle real life use cases like reverse proxy usage, server containerization and elaborate backend setups.

## Origin Document

The new config discussion happened in this page:
https://www.notion.so/buildwithgrove/Actors-configs-dependencies-etc-ab9a93322b8744a2aaa089d5b4758b75?pvs=4#8eaa5c5a3f4743319cc1e8360d058be3

Final config structure proposed:
https://github.com/pokt-network/poktroll/pull/246

```yaml
pocket:
  query_node_rpc_url: tcp://localhost:36657
  query_node_grpc_url: tcp://127.0.0.1:36658
  tx_node_grpc_url: tcp://127.0.0.1:36658
signing_key_name: servicer1
proxies:
  - name: http-example
    host: 127.0.0.1
    port: 8080
    type: http 
suppliers:
  - name: ethereum
    type: http
    service_config:
      url: http://anvil.servicer:8545
      authentication:
        username: user
        password: pwd
      headers: {}
    hosts:
      - ethereum.devnet1.poktroll.com 
      - ethereum # <- this part can be added automatically.
    proxy_names:
      - http-example # when the RelayMiner server builder runs.
  - name: 7b-llm-model
    type: http
    service_config:
      url: http://llama-endpoint
    hosts:
      - 7b-llm-model.devnet1.poktroll.com 
      - 7b-llm-model # <- this part can be added automatically.
    proxy_names:
      - http-example # when the RelayMiner server builder runs.
```

## Goals

- Be able to parse the new config structure
- Adapt the `RelayerProxy` to handle the new configuration and start the adequate servers

## Deliverables

- [x] PR for parsing the config into the adequate structure
- [x] PR for adapting the `RelayerProxy` to use the new config

## Non-goals / Non-deliverables

- Implement additional types other than `http`
- Implement authentication mechanisms beyond basic auth

## General deliverables

- [x] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [x] **Testing**: Add new tests (unit and/or E2E) to the test suite.

---

**Creator**: @red-0ne
**Co-Owners**: @okdas
