### ISSUE TITLE
[Infra] Rollkit image used in LocalNet fails DNS name resolution of kubernetes services 

### ISSUE THREAD

**Issue by adshmh** [pokt-network/poktroll#301]
## Objective

Celestia secret is created by the `secret-update-sidecar` container.

## Origin Document

The `secret-update-sidecar` container fails to create the Celestia secret, causing failure in downstream containers like Sequencer. This seems to be due to DNS name resolution failing for k8s services in the Rollkit image used in LocalNet.

Pod used for testing:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: default
spec:
  containers:
  - name: dnsutils
    image: ghcr.io/rollkit/local-celestia-devnet:v0.12.1
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
```

Name resolution failure:

```bash
kubectl exec -it pod/dnsutils -- /bin/bash -c 'nslookup kubernetes.default'
Server:         10.96.0.10
Address:        10.96.0.10:53

** server can't find kubernetes.default: NXDOMAIN
```

The same pod template, with a different image, succeeds (image from https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/)

```image:  registry.k8s.io/e2e-test-images/jessie-dnsutils:1.3```

Name resolution success:

```
kubectl exec -it pod/dnsutils -- /bin/bash -c 'nslookup kubernetes.default'
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   kubernetes.default.svc.cluster.local
Address: 10.96.0.1
```

## Goals

- The `update-secret-sidecar` container should successfully create the secret.

## Deliverables

- [ ] The Celestia secret is successfully created, allowing the subsequent containers to operate normally.

**Creator**: @adshmh 
**Co-Owners**: @okdas @Olshansk
