### ISSUE TITLE
[RelayMiner] Unable to start RelayMiner

### ISSUE THREAD

**Issue by okdas** [pokt-network/poktroll#499]
## Objective

Originally reported by the community member @breezytm and also verified on another deployment.

## Origin Document

https://discord.com/channels/553741558869131266/1217918754801975398/1233196393972367482

## What we're seeing

When RelayMiner starts, it doesn't open the port to serve the requests, though the configuration looks as desired.

Config by community member: https://discord.com/channels/553741558869131266/1217918754801975398/1233197837613924473

Config I've replicated an issue with:
```
# Please refer to https://dev.poktroll.com/configs/relayminer_config for documentation.
signing_key_name: key-for-relayminer1
smt_store_path: smt_stores
pocket_node:
  query_node_rpc_url: tcp://poktrolld:26657
  query_node_grpc_url: tcp://poktrolld:26658
  tx_node_rpc_url: tcp://poktrolld:26657
suppliers:
- service_id: "0021" # 0021 is an Ethereum mainnet service ID. Other legacy IDs: https://docs.pokt.network/reference/supported-chains
  service_config:
    backend_url: "http://eth-mainnet.rpc.grove.city/v1/XXXX" # Ethereum mainnet RPC endpoint to forward relays to. E.g. http://etherium-node:8547/
    publicly_exposed_endpoints:
    - 167.235.227.77 # Hostname or IP address. You want this to match the address from the supplier stake config.
  listen_url: http://0.0.0.0:8545 # You can replace `0.0.0.0` with a different network interface if you don't want to open port on all network interfaces.
metrics:
  enabled: true
  addr: :9090
pprof:
  enabled: true
  addr: :6060

```

Logs:
```
relayminer-example-1  | {"level":"info","endpoint":":6060","message":"starting a pprof endpoint"}
relayminer-example-1  | {"level":"info","endpoint":":9090","message":"serving metrics"}
```
Nothing else.

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @okdas 
**Co-Owners**: @red-0ne

**Comment by okdas** [comment]
I also noticed RelayMiner is unable to start when I configure an HTTPS `backend_url`

```
suppliers:
- service_id: "0021" # 0021 is an Ethereum mainnet service ID. Other legacy IDs: https://docs.pokt.network/reference/supported-chains
  service_config:
    backend_url: "https://eth-mainnet.rpc.grove.city/v1/XXXX" # Ethereum mainnet RPC endpoint to forward relays to. E.g. http://etherium-node:8547/
```


Error I see when that happens: `invalid supplier type https: invalid supplier in RelayMiner config [/go/pkg/mod/cosmossdk.io/errors@v1.0.1/errors.go:155]`
