### ISSUE TITLE
[RelayMiner] RelayMiner Lean Client

### ISSUE THREAD

**Issue by RawthiL** [pokt-network/poktroll#528]
## Objective

Enable a `N:1 Supplier:RelayMiner` relation, i.e. connect multiple Suppliers to the same RelayMiner process.

This is required for mid-large node runners operations and economical constraints.

## Origin Document

[This comment](https://github.com/pokt-network/poktroll/pull/524/files#diff-d93c4dd4583de84916aab1b03b2819c4d53aff7aa4e269af16648ac1c75b7c06R157) refers the a `N:1 Supplier:RelayMiner` relation as "not okay"  when it is fundamental for mid-large node runners.

Without this feature the hardware costs of these operations will be at least 6 times higher due to hardware requirements.

More context [at this discord thread](https://discord.com/channels/553741558869131266/1234943674903953529/1239636373825257654).

Related Lean Pocket data:
- Morse Issue: https://github.com/pokt-network/pocket-core/issues/1437
- Forum discussion of original problem that lead to LeanPOKT: https://forum.pokt.network/t/optimizing-the-v0-client-to-save-the-network-a-ton-of-money/2510
- Morse Implementation
	- https://github.com/pokt-network/pocket-core/pull/1463
	- https://github.com/pokt-network/pocket-core/pull/1488

## Goals

- Allow the connection of multiple Suppliers to a single RelayMiner
- A single RelayMiner process should be at least able to handle 700 Supliers to match LeanPOKT capabilities
- Reduce the costs for RelayMiner operators that support multiple Suppliers

## Deliverables

- [ ] A PR to enable the RelayMiner process to have multiple signing `Supplier`s:
  - Update the config parser code (`pkg/relayer/config`) to:
    - Allow `signing_key_names` array in the `suppliers` entries.
    - Have a top level `default_signing_key_names` that act as a default value for the `suppliers` entries that lack `signing_key_names`
  - Update the `RelayRequestMetadata` proto (`proto/poktroll/relay.proto`) to add the `supplier_address` field
  - Update the `relayerProxy` struct (`pkg/relayer/proxy`) to:
    - Remove the `rp.signingKeyName` entry.
    -  Use `rp.serverConfigs.SupplierConfigsMap` as a source of truth for the available signing keys
    - Check that `RelayRequestMetadata.SupplierAddress` is effectively present in `rp.serverConfigs.SupplierConfigsMap[ServiceId].SigningKeyNames` and serving the requested `ServiceId`
    - Leverage `RelayRequestMetadata.SupplierAddress` to pick the right signing `Supplier`
- [ ] Support at least 700 Servicers reporting at current Morse net rate.

## Non-goals / Non-deliverables

- Enable anything related to `GeoMesh`. This is a `LeanPOKT` parity only.

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @RawthiL 
**Co-Owners**: @jorgecuesta

**Comment by Olshansk** [comment]
Thanks for bringing this up @RawthiL and @jorgecuesta!

I updated some parts of the issue, but for reference, here is the implementation in Morse: https://github.com/pokt-network/pocket-core/pull/1463/files

After synching on this with @okdas, we believe this should be "as simple as" the business logic that would accompany the following configuration changes:

```diff
- signing_key_name: supplier1
+ default_signing_key_name: supplier1
smt_store_path: smt_stores
metrics:
  enabled: true
  addr: :9090
pocket_node:
  query_node_rpc_url: tcp://127.0.0.1:36657
  query_node_grpc_url: tcp://127.0.0.1:36658
  tx_node_rpc_url: tcp://127.0.0.1:36657
suppliers:
  - service_id: anvil
+ # implicitly supplier1
    listen_url: http://localhost:6942
    service_config:
      backend_url: http://localhost:8081
      publicly_exposed_endpoints:
        - localhost
  - service_id: svc2
+  signing_key_name: supplier2
    listen_url: http://localhost:6943
    service_config:
      backend_url: http://localhost:8082
      publicly_exposed_endpoints:
        - notlocalhost
pprof:
  enabled: false
  addr: localhost:6060
  ```

**Comment by red-0ne** [comment]
With some additional specs w.r.t. how to route the request to the right supplier, this is how I imagined it could be.

**Comment by red-0ne** [comment]
Given that:
1. We can't prevent different `Supplier`s from staking with the same `service_id`.
2. We can't prevent different `Supplier`s to have the same `publicly_exposed_endpoint`.
3. Our current implementation allows having different services being handled by the same `listen_url` (which is great for lean clients).


Assuming that we have a config with 2 `Supplier`s in our lean client like the following:
```yaml
suppliers:
  - service_id: anvil
    signing_key_name: supplier1
    listen_url: http://localhost:9999
    service_config:
      backend_url: http://localhost:8081
      publicly_exposed_endpoints:
        - leanclienthost

  - service_id: anvil
    signing_key_name: supplier2
    listen_url: http://localhost:9999
    service_config:
      backend_url: http://localhost:8082
      publicly_exposed_endpoints:
        - leanclienthost
```

Here, both `Supplier`s provide the same `service_id` on the same `listen_url` and `publicly_exposed_endpoints`. Which makes it ambiguous on how to select which `Supplier` will be signing requests.

With the idea of:
1. Keeping this config structure (because it's simple and awesome).
2. Not adding any in-chain checks or restrictions when staking (unique `publicly_exposed_endpoints` across different `Supplier`s).
3. Not enforcing unique `listen_url`s in the config. Because we'd have to run 2500 HTTP servers if we want to collocate 2500 different `Supplier`s

We're left with a few solutions:
1. Enforce **in the config** that different `Suppliers`s do not provide the same `service_id`. If `supplier1` provides `svc1`, then `supplier2` cannot. (I personally don't like this solution and suspect lean client operators would want to have multiple `Supplier`s with for the same `service_id`)
2. Add a `supplier_address` field in the `RelayRequest` proto like the following
```diff
message RelayRequest {
  RelayRequestMetadata meta = 1 [(gogoproto.nullable) = false];
  bytes payload = 2;
+ string supplier_address = 3;
}
```
Which will be populated by the `Gateway` when selecting a `Supplier` for a `RelayRequest`.

This is possible because:
1. We select the `Supplier` (url) before signing the `RelayRequest`
2. We can omit the `supplier_address` field from the signable bytes if we want to sign before selecting a `Supplier` or keep the relay request acceptable by any `Supplier` from the `Session`.

I believe the later is the simplest solution, and the most direct path to have lean clients given our current implementation.

**Comment by jorgecuesta** [comment]
> I believe the later is the simplest solution, and the most direct path to have lean clients given our current implementation.

- I agree here, add the `supplier_address` like right now is happening on the relays. 
- `publicly_exposed_endpoints` and `listen_urls` should not be considered as unique, to be honest.
- Limiting the Supplier & Service ID combination as unique per RelayMiner is a terrible idea for mid-large node runners.

**Comment by okdas** [comment]
@red-0ne is there any way to get information about which supplier relay is arriving for using `RelayRequestMetadata`? Seems like the `Session` has a list of `Suppliers`:

```
repeated poktroll.shared.Supplier suppliers = 6;
```

I think we can match/route to suppliers on RelayMiner based on that array. Or am I thinking nonsense? 

Btw, if we translate the current (Morse) lean pocket client to the relay miner config it would look like this:

```
suppliers:
  - service_id: anvil
    signing_key_name: supplier1
    listen_url: http://localhost:9999
    service_config:
      backend_url: http://localhost:8081
      publicly_exposed_endpoints:
        - leanclienthost1

  - service_id: anvil
    signing_key_name: supplier2
    listen_url: http://localhost:9999
    service_config:
      backend_url: http://localhost:8081
      publicly_exposed_endpoints:
        - leanclienthost2
```

Difference between your snippet and that snippet are:
- Different suppliers use different `publicly_exposed_endpoints` - that is currently requests are routed.
- All services use the same `backend_url` to relay requests to.
