### ISSUE TITLE
[Protobufs] Ensure deterministic serialization

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#761]
## Objective

Prevent chain halts by ensuring deterministic serialization.

## Origin Document

https://discord.com/channels/824324475256438814/1138895490331705354/1276711734601580614

<img width="1148" alt="Screenshot 2024-08-23 at 10 17 49 PM" src="https://github.com/user-attachments/assets/27785da3-f401-4faa-8bd5-528c23108b97">

## Goals

- Prevent chain halts by ensuring deterministic serialization.
- Prevent these sorts of issues in the future (e.g. preferably through automation rather than documentation)

## Deliverables

- [x] Research whether the addition of `option (gogoproto.stable_marshaler) = true;` is still the right way to serialize.
- [x] Determine if this is needed for lists, maps or both
- [ ] Find a way to enforce have this flag for all protobufs with lists and/or maps (e.g.  a github workflow)
  - [x] A PR which implements a tool and makefile targets for identifying and fixing "unstable marshalers" in all protobuf files
    - #770 
  -  [x] A PR which commits fixes for existing "unstable marshalers"
    - #772 
  - [ ] A PR which adds incorporates the check for "unstable marshalers" in protobuf files into the linting CI job
  - [ ] A PR which adds a checklist item to the PR template regarding self-review of changes related to repeated protobuf message fields
    - #773 

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @Olshansk 
**Co-Owners**: @okdas @bryanchriswhite

**Comment by Olshansk** [comment]
@okdas Saw your comment here: https://github.com/pokt-network/poktroll/issues/759#issuecomment-2313334858

Wanted to follow up on next steps.
1. Do we need to ensure `nullable = true` everywhere?
2. Do we need to ensure `stable_marshaler = true` everywhere?
3. Is there anything else we need to do?

**Comment by okdas** [comment]
@Olshansk good question — let me double check the stable marshaller.

**Comment by bryanchriswhite** [comment]
@okdas @Olshansk My investigation seems to indicate that `(gogoproto.stable_marshaler)` **is necessary** in order to ensure marshaling results are consistent, which is the hypothetical explanation for the app state hash inconsistency I've been working under thus far. I have been able to:

1. Prove that the presence or absence of the `stable_marshaler` option indeed results in consistent and inconsistent hashes of the resulting serialized data, repsectively, via unit tests.
2. Develop a methodology to programatically (and robustly) identify protobuf message types which do not have this option.
3. Develop a methodology for discovering which protobuf messages are actually ever stored in the network state (multistore).

Point 3. Turns out to be more challenging than I expected but It's pretty far along nonetheless. I shifted away from 3. to prioritize 2. and initially target all protobuf messages which don't match the following regex `^(?:Module|(?:Query|Request|Response|Event|Msg)\w+$)`. Using this regex filter (instead of the more target approach afforded by 3.) narrows down the number of message types that need updating; however:
  1. It likely includes message types which are not ever stored in network state (false positives).
  2. It may exclude nested protobuf message types which are stored in network state (false negatives).

### Options at this point:
1. Add the `stable_marshaler` option to all message types (i.e. ignore regex filter) (SAFEST, FASTER, UGLIEST?).
2. Add the `stable_marshaler` option to filtered message types (FASTEST).
3. Continue with next steps (below).

### Next steps:
1. Recursively follow nested protobuf types to eliminate false negatives (but not false positives).
2. Complete 3. to eliminate false positives.

**Comment by bryanchriswhite** [comment]
```
Recursively checking for files matching "*.proto" in "./proto"
Unstable marshalers found:
        proto/poktroll/gateway/genesis.proto:
                GenesisState: proto/poktroll/gateway/genesis.proto:13
        proto/poktroll/proof/params.proto:
                Params: proto/poktroll/proof/params.proto:11
        proto/poktroll/shared/params.proto:
                Params: proto/poktroll/shared/params.proto:10
        proto/poktroll/supplier/genesis.proto:
                GenesisState: proto/poktroll/supplier/genesis.proto:13
        proto/poktroll/supplier/params.proto:
                Params: proto/poktroll/supplier/params.proto:10
        proto/poktroll/tokenomics/genesis.proto:
                GenesisState: proto/poktroll/tokenomics/genesis.proto:13
        proto/poktroll/gateway/params.proto:
                Params: proto/poktroll/gateway/params.proto:10
        proto/poktroll/proof/genesis.proto:
                GenesisState: proto/poktroll/proof/genesis.proto:13
        proto/poktroll/proof/types.proto:
                Proof: proto/poktroll/proof/types.proto:14
                Claim: proto/poktroll/proof/types.proto:24
        proto/poktroll/service/params.proto:
                Params: proto/poktroll/service/params.proto:11
        proto/poktroll/application/genesis.proto:
                GenesisState: proto/poktroll/application/genesis.proto:13
        proto/poktroll/service/genesis.proto:
                GenesisState: proto/poktroll/service/genesis.proto:14
        proto/poktroll/session/genesis.proto:
                GenesisState: proto/poktroll/session/genesis.proto:12
        proto/poktroll/session/params.proto:
                Params: proto/poktroll/session/params.proto:10
        proto/poktroll/shared/genesis.proto:
                GenesisState: proto/poktroll/shared/genesis.proto:11
        proto/poktroll/tokenomics/params.proto:
                Params: proto/poktroll/tokenomics/params.proto:10
        proto/poktroll/application/params.proto:
                Params: proto/poktroll/application/params.proto:10
        proto/poktroll/application/types.proto:
                Application: proto/poktroll/application/types.proto:17
                UndelegatingGatewayList: proto/poktroll/application/types.proto:38
        proto/poktroll/gateway/types.proto:
                Gateway: proto/poktroll/gateway/types.proto:13
        proto/poktroll/service/relay.proto:
                Relay: proto/poktroll/service/relay.proto:13
                RelayRequestMetadata: proto/poktroll/service/relay.proto:19
                RelayRequest: proto/poktroll/service/relay.proto:36
                RelayResponse: proto/poktroll/service/relay.proto:45
                RelayResponseMetadata: proto/poktroll/service/relay.proto:54
        proto/poktroll/session/types.proto:
                SessionHeader: proto/poktroll/session/types.proto:20
                Session: proto/poktroll/session/types.proto:35
        proto/poktroll/shared/service.proto:
                Service: proto/poktroll/shared/service.proto:12
                ApplicationServiceConfig: proto/poktroll/shared/service.proto:32
                SupplierServiceConfig: proto/poktroll/shared/service.proto:42
                SupplierEndpoint: proto/poktroll/shared/service.proto:52
                ServiceRevenueShare: proto/poktroll/shared/service.proto:59
                ConfigOption: proto/poktroll/shared/service.proto:83
        proto/poktroll/tokenomics/relay_mining_difficulty.proto:
                RelayMiningDifficulty: proto/poktroll/tokenomics/relay_mining_difficulty.proto:8
```
